{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Quantidade de pesquisas respondidas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "counter_answered_reports_on_a_day",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quantidade de pesquisas enviadas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "quantity_of_surveys_sent_hour_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quantidade de erros que deram na distribuição",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantity_of_request_error_distribution",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo de reposta da rota de upload de planilha",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "route_response_time_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}